ClothBazar.Web/Controllers/ProductController.cs
using ClothBazar.Entities;
using ClothBazar.Services;
using ClothBazar.Web.HomeModelViews;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class ProductController : Controller
    {
       // ProductsService productsService = new ProductsService();
      //  CategoriesService categoryservice = new CategoriesService();

        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProductList(string search,int? pageNo)
        {
            var pageSize = ConfigurationService.Instance.PageSize();
            ProductSearchViewModels model = new ProductSearchViewModels();
            model.SearchTerm = search;
            //check page value otherwise 1 value assign
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;

            //Example one line if condition
            //if (pageNo.HasValue)
            //{
            //    if (pageNo.Value > 0)
            //    {
            //        model.pageNo = pageNo.Value;
            //    }
            //    else
            //    {
            //        model.pageNo = 1;
            //    }
            //}
            //else
            //{
            //   model.pageNo = 1;
            //}

    
            var totalRecords = ProductsService.Instance.GetAllProductCount(search);
            model.Products = ProductsService.Instance.GetAllProduct(search, pageNo.Value, pageSize);

            model.Pager = new Pager(totalRecords,pageNo, pageSize );
        
            return PartialView(model);
        }

        public ActionResult Create()
        {
            ProductViewModels model = new ProductViewModels();
         //   CategoriesService categoryservice = new CategoriesService();
            model.AvailableCategories = CategoriesService.Instance.GetAllCategory();
            
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Create(ProductViewModels model)
        {
            if (ModelState.IsValid)
            {
               // CategoriesService categoryservice = new CategoriesService();

                var newProduct = new Product();
                newProduct.Name = model.Name;
                newProduct.Description = model.Description;
                newProduct.Price = model.Price;
                newProduct.Category = CategoriesService.Instance.GetCategoryID(model.CategoryID);
                newProduct.ImageURL = model.ImageURL;

                ProductsService.Instance.SaveProduct(newProduct);
            }
            return RedirectToAction("ProductList");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            EditProductViewModel model = new EditProductViewModel();
            
            var product = ProductsService.Instance.GetProductID(id);
            model.ID = product.ID;
            model.Name = product.Name;
            model.Description = product.Description;
            model.Price = product.Price;
            model.CategoryID = product.Category != null ? product.Category.ID :0;
            model.ImageURL = product.ImageURL;

            model.AvailableCategories = CategoriesService.Instance.GetAllCategory();

            return PartialView(model); 
        }
        [HttpPost]
        public ActionResult Edit(EditProductViewModel model)
        {
            if (ModelState.IsValid)
            {
               // CategoriesService categoryservice = new CategoriesService();

                var existingProduct = ProductsService.Instance.GetProductID(model.ID);
                existingProduct.Name = model.Name;
                existingProduct.Description = model.Description;
                existingProduct.Price = model.Price;
                existingProduct.CategoryID = model.CategoryID;
              //  existingProduct.ImageURL = model.ImageURL;

                if (!string.IsNullOrEmpty(model.ImageURL))
                {
                    existingProduct.ImageURL = model.ImageURL;
                }
                ProductsService.Instance.GetProductUpdate(existingProduct);
            }
            return RedirectToAction("ProductList");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            ProductsService.Instance.GetProductDelete(id);
            return RedirectToAction("ProductList");
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            ProductViewModel model = new ProductViewModel();

            model.Product = ProductsService.Instance.GetProductID(id);
            return View(model);
        }

    }
}

ClothBazar.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class SharedController : Controller
    {
        // GET: Shared
        public JsonResult  UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            try
            {
                var file = Request.Files[0];
                var filename = Guid.NewGuid() + Path.GetExtension(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/Images"),filename);
                file.SaveAs(path);
                result.Data = new
                {
                    Success = true,
                    ImageURL = string.Format("/Content/Images/{0}",filename)
                };
            }
            catch (Exception ex)
            {
                result.Data = new
                {
                    Success = false,
                    Message = ex.Message
                };
            }
            return result;
        }
    }
}

ClothBazar.Web/Views/Product/Create.cshtml
@model ProductViewModels
@{
    ViewBag.Title = "Create";
    var imageURL = "/Content/Images/Default_image.jpg";
}
<h2>Create Product</h2>
<form id="createProduct" class="form-inline" >
    <div class="form-group mb-2 ml-5">
        <select name="CategoryID">
            @foreach (var category in Model.AvailableCategories)
            {
                <option value="@category.ID">@category.Name</option>
            }
        </select>

        <label>Name</label>
        <input type="text" name="name" />


        <label>Description</label>
        <input type="text" name="Description" />


        <label>Price</label>
        <input type="text" name="Price" />

        <label>Image</label>
        <input class="form-control form-control-lg" type="hidden" id="ImageURL" name="ImageURL" />
        <input class="form-control form-control-lg" id="changeimg" type="file" name="image" accept=".png .jpg" />
        <div class="thumb w-25 h-25 ">
            <img id="imageshow" src="@imageURL" />
        </div>

        <button id="savebtn" type="button" class="btn btn-primary form-control form-control-sm">Save</button>
        <button id="cancelbtn" type="button" class="btn btn-primary form-control form-control-sm">Cancel</button>

    </div>
</form>


<script>

    $("#changeimg").change(function () {

        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;

        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }

        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")',//'/Shared/UploadImage',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        }).done(function (response) {

            console.log(response);

            if (response.Success) {
                $("#ImageURL").val(response.ImageURL);
                $("#imageshow").attr("src", response.ImageURL);
            }

        }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        })
    })

    $("#savebtn").click(function () {
        $.ajax({
            type:'POST',
            url:  '@Url.Action("Create", "Product")',//'/Product/Create',
            data: $("#createProduct").serialize()
        }).done(function (response) {
            $("#tableContiner").html(response);
            $("#createProduct").html("");
            focusAction("tableContiner");
        }).fail(function (XMLHttpRequest,textStatus,errorThrown) {
            alert("FAIL");
        })
    });


    $("#cancelbtn").click(function () {
        $("#AddProductCon").html("");
        focusAction("tableContiner");
    });

</script>

ClothBazar.Web/Views/Product/Edit.cshtml
@model EditProductViewModel
@{
    ViewBag.Title = "Edit";
    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/Images/Default_image.jpg";
}


@*<form id="editProduct">
    <h2>Edit Product</h2>

    <input type="hidden" name="ID" value="@Model.ID"/>

    <label>Name</label>
    <input type="text" name="name" value="@Model.Name"/>


    <label>Description</label>
    <input type="text" name="Description" value="@Model.Description"/>


    <label>Price</label>
    <input type="text" name="Price" value="@Model.Price"/>

    <button id="editbtn" type="button">Update</button>
</form>*@

<form id="editProduct" class="form-inline">
    <input type="hidden" name="ID" value="@Model.ID" />

    <div class="form-group mb-2 ml-5">
        <label>Category</label>
        <select name="CategoryID">
            @foreach (var category in Model.AvailableCategories)
            {
                var selected = category.ID == Model.CategoryID ? "selected" : string.Empty;
                <option value="@category.ID" @selected>@category.Name</option>
            }
        </select>

        <label>Name</label>
        <input type="text" name="name" value="@Model.Name" />


        <label>Description</label>
        <input type="text" name="Description" value="@Model.Description" />


        <label>Price</label>
        <input type="text" name="Price" value="@Model.Price" />

        <label>Image</label>
        <input class="form-control form-control-lg" type="hidden" id="ImageURL" name="ImageURL" value="@Model.ImageURL" />
        <input class="form-control form-control-lg" id="changeimg" type="file" name="image" accept=".png .jpg" />
        <div class="thumb w-25 h-25 ">
            <img id="imageshow" src="@imageURL" />
        </div>

        <button id="editbtn" type="button" class="btn btn-primary form-control form-control-lg">Update</button>
        <button id="cancelbtn" type="button" class="btn btn-primary form-control form-control-lg">Cancel</button>

    </div>
</form>

<script>
    $("#changeimg").change(function () {

        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;

        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }

        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")',//'/Shared/UploadImage',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        }).done(function (response) {

            console.log(response);

            if (response.Success) {
                $("#ImageURL").val(response.ImageURL);
                $("#imageshow").attr("src", response.ImageURL);
            }

        }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        })
    })

    $("#editbtn").click(function () {
        $.ajax({
            type:'POST',
            url:   '@Url.Action("Edit", "Product")',//'/Product/Edit',
            data: $("#editProduct").serialize()
        }).done(function (response) {
            $("#tableContiner").html(response);
            $("#editProduct").html("");
            focusAction("tableContiner");
        }).fail(function (XMLHttpRequest,textStatus,errorThrown) {
            alert("FAIL");
        })
    });

    $("#cancelbtn").click(function () {
        $("#AddProductCon").html("");
        focusAction("tableContiner");
    });
</script>

ClothBazar.Web/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Products";
}

@*<h2>Product Home Page</h2>*@

<section class="flat-row flat-iconbox">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section margin_bottom_17">
                    <h2 class="title">
                        Product
                    </h2>
                </div>
            </div>
        </div>
        @{
            Html.RenderAction("ProductList");
            //  Html.RenderAction("Create");
        }
     </div>
</section>

ClothBazar.Web/Views/Product/ProductList.cshtml
@model ProductSearchViewModels

<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css"/>
<script src="//cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>

@*<script src="~/Scripts/jquery-1.10.2.js"></script>*@

<div id="tableContiner">

    <div class="container">
        <form class="form-inline" method="post">
            <div class="form-group mb-2 ">
                <input id="searchtxt" class="form-control" name="Search" value="@Model.SearchTerm" />
                <button class="btn btn-primary ml-1" type="button" id="search">Search</button>
                <button class="btn btn-primary ml-1" type="button" id="reset">Reset</button>
                <button class="btn btn-primary ml-1" type="button" id="NewBtn" >New</button>
            </div>
        </form>
    </div>
    <div >
        <table id="ProductsTable" class="table table-striped">
            <thead>
                <tr>
                    <th class="font-weight-bold">Product Name</th>
                    <th class="font-weight-bold">Category</th>
                    <th class="font-weight-bold">Price</th>
                    <th class="font-weight-bold wrap-td">Actions</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Products != null && Model.Products.Count > 0)
            {
                foreach (var product in Model.Products)
                {
                        <tr>
                            <td>@product.Name</td>
                            <td>
                                @if (product.Category != null)
                                {
                                    <text>@product.Category.Name</text>
                                }
                                else
                                {
                                    <text>-</text>
                                }
                            </td>
                            <td>@product.Price</td>
                            <td class="wrap-td">
                                <button class="EditBtn" data-id="@product.ID">Edit</button>
                                <button class="DelBtn" data-id="@product.ID">Delete</button>
                                <button class="addtoCart" data-id="@product.ID">Add To Card</button>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="4" class="text-danger">No Product found.</td>
                    </tr>
                }
            </tbody>
        </table>
        <div>
      
            @if (Model.Pager != null && Model.Pager.TotalPages > 1)
            {
                if (Model.Pager.CurrentPage > 1)
                {
                    <button class="pageRecords" data-pageno="1">First</button>
                    <button class="pageRecords" data-pageno="@(Model.Pager.CurrentPage - 1)">Previous</button>
                }
                for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                {
                    string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                    <button class="@activeClass pageRecords" data-pageno="@page">@page</button>
                }
                if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                {
                    <button class="pageRecords" data-pageno="@(Model.Pager.CurrentPage + 1)">Next</button>
                    <button class="pageRecords" data-pageno="@(Model.Pager.EndPage)">Last</button>
                }
            }
        </div>
    </div>
  
</div>
<div id="AddProductCon">

</div>


<script>

    //$('#ProductsTable').DataTable();


    $(".pageRecords").click(function () {
        $.ajax({
            url: '@Url.Action("ProductList", "Product")',
            data: {
                pageNo: $(this).attr("data-pageno")
            }
        })
        .done(function (response) {
            $("#tableContiner").html(response);
        })

        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        })
    });



    $("#search").click(function () {
        var txtvalue = $("#searchtxt").val();
        $.ajax({
            url: '@Url.Action("ProductList", "Product")',
            data: {
                search: txtvalue
            }
        }).done(function (data) {

            $("#tableContiner").html(data);
            //alert(data);
        }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        })

    });

    $("#reset").click(function () {
        var txtvalue = '';
        $.ajax({
            url: '@Url.Action("ProductList", "Product")',
            data: {
                search: txtvalue
            }
        }).done(function (data) {

            $("#tableContiner").html(data);
        }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        })

    });

    $("#NewBtn").click(function () {
        $.ajax({
            url: '@Url.Action("Create", "Product")',
        })
        .done(function (response) {
            $("#AddProductCon").html(response);
            focusAction("AddProductCon");
        })

        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        })
    });

    $(".EditBtn").click(function () {
        $.ajax({
            url:  '@Url.Action("Edit", "Product")',
            data: {
                ID: $(this).attr('data-id')
            }
        })
        .done(function (response) {
            $("#AddProductCon").html(response);

            focusAction("AddProductCon");

        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        })
    });

    $(".DelBtn").click(function () {

            swal({
                title: "Are you sure?",
                text: "Are you sure you want to delete this product?",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {

                        $.ajax({
                            type: 'POST',
                            url:  '@Url.Action("Delete", "Product")',
                            data: {
                                ID: $(this).attr('data-id')
                            }
                        })
                        .done(function (response) {
                            $("#tableContiner").html(response);
                            swal("Record deleted Successfully.!", {
                                icon: "success",
                        })
                        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                            alert("FAIL");
                        })

                    });
                }
            });

        //var confirmsms = confirm("Are you sure you want to delete this product?");

        //if (confirmsms) {
        //    $.ajax({
        //        type: 'POST',
        //        url: '/Product/Delete',
        //        data: {
        //            ID: $(this).attr('data-id')
        //        }
        //    })
        //   .done(function (response) {
        //       $("#tableContiner").html(response);
        //   })
        //   .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        //       alert("FAIL");
        //   })
        //}

    });

    var products = [];
    $(".addtoCart").click(function () {

        var productID = $(this).attr('data-id');
        products.push(productID);
        $.cookie('CartProducts', products.join('-'), { path: '/' });
        alert('Product Addd to Cart.');
    });

    function focusAction(controlToFocus) {
        $('html , body').animate({
            scrollTop: $("#" + controlToFocus).offset().top - 100
        }, 1000);
    }
    //function focusAction() {
    //    $('html , body').animate({
    //        scrollTop: $("#AddProductCon").offset().top - 100
    //    }, 1000);
    //}
</script>