ClothBazar.Web/Controllers/CategoryController.cs
using ClothBazar.Entities;
using ClothBazar.Services;
using ClothBazar.Web.HomeModelViews;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CategoryList(string search,int? pageNo)
        {
            CategorySearchViewModels model = new CategorySearchViewModels();
            model.SearchTerm = search;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;

            var totalRecords = CategoriesService.Instance.GetAllCategoryCount(search);
            model.Categories = CategoriesService.Instance.GetAllCategory(search,pageNo.Value);

          
            if (model.Categories !=null)
            {
                model.Pager = new Pager(totalRecords, pageNo,2);
                return PartialView("_CategoryList", model);
            }
            else
            {
                return HttpNotFound();
            }
        
        }

        [HttpGet]
        public ActionResult Create()
        {
            CategoryViewModels model = new CategoryViewModels();
        //    CategoriesService categoryservice = new CategoriesService();
          
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Create(CategoryViewModels model)
        {
            if (ModelState.IsValid)
            {
                var newcategory = new Category();
                newcategory.Name = model.Name;
                newcategory.Description = model.Description;
                newcategory.ImageURL = model.ImageURL;
                newcategory.IsFeatured = model.isFeatured;

                CategoriesService.Instance.SaveCategory(newcategory);
                return RedirectToAction("CategoryList");
            }
            else
            {
                return new HttpStatusCodeResult(500);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            EditCategoryViewModels model = new EditCategoryViewModels();

            var category = CategoriesService.Instance.GetCategoryID(id);

            model.ID = category.ID;
            model.Name = category.Name;
            model.Description = category.Description;
            model.ImageURL = category.ImageURL;
            model.isFeatured = category.IsFeatured;

            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Edit(EditCategoryViewModels model)
        {
           
            if (ModelState.IsValid)
            {

                var existingCategory = CategoriesService.Instance.GetCategoryID(model.ID);
                existingCategory.Name = model.Name;
                existingCategory.Description = model.Description;
                existingCategory.ImageURL = model.ImageURL;
                existingCategory.IsFeatured = model.isFeatured;

                CategoriesService.Instance.GetCategoryUpdate(existingCategory);

            }
            return RedirectToAction("CategoryList");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            CategoriesService.Instance.GetCategoryDelete(id);
            return RedirectToAction("CategoryList");
        }
    }
}

ClothBazar.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class SharedController : Controller
    {
        // GET: Shared
        public JsonResult  UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            try
            {
                var file = Request.Files[0];
                var filename = Guid.NewGuid() + Path.GetExtension(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/Images"),filename);
                file.SaveAs(path);
                result.Data = new
                {
                    Success = true,
                    ImageURL = string.Format("/Content/Images/{0}",filename)
                };
            }
            catch (Exception ex)
            {
                result.Data = new
                {
                    Success = false,
                    Message = ex.Message
                };
            }
            return result;
        }
    }
}

ClothBazar.Web/Views/Category/Create.cshtml
@model CategoryViewModels

@{
    ViewBag.Title = "Create";

    //var truechecked = Model.IsFeatured ? "checked" : string.Empty;
    //var falsechecked = !Model.IsFeatured ? "checked" : string.Empty;
    var imageURL = "/Content/Images/Default_image.jpg";
}

@*<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>*@

@*<form method="post">
    <h2>Create Category</h2>

    <label>Name</label>
    <input type="text" name="name" />


    <label>Description</label>
    <input type="text" name="Description" />

    <label>Is Featured</label>
    <input name="IsFeatured" type="radio" value="True" checked   /> True
    <input name="IsFeatured" type="radio" value="False"  /> False <br/>

    <label>Image</label>
    <input id="ImageURL" type="hidden" name="ImageURL"/>
    <input id="changeimg" type="file" name="image" accept=".png .jpg"/>

    <img id="imageshow"/>

    <button type="submit">Save</button>

</form>*@

<form id="createCategory" >
    <div class="mb-2 ml-5">

        <label>Name</label>
        <input class="form-control form-control-lg" type="text" name="name" />


        <label>Description</label>
        <input class="form-control form-control-lg" type="text" name="Description" />

        <label>Is Featured</label><br />
        <input name="IsFeatured" type="radio" value="True" checked /> True
        <input name="IsFeatured" type="radio" value="False" /> False 
        <br />
        <label>Image</label>
        <input class="form-control form-control-lg" type="hidden"  id="ImageURL" name="ImageURL" />
        <input class="form-control form-control-lg" id="changeimg" type="file" name="image" accept=".png .jpg" />
        <div  class="thumb w-25 h-25 ">
            <img id="imageshow" src="@imageURL"  />
        </div>
        <br />
        <button id="savebtn" type="button" class="btn btn-primary form-control form-control-sm">Save</button>
        <button id="cancelbtn" type="button" class="btn btn-primary form-control form-control-sm">Cancel</button>

    </div>
</form>


<script>

    $("#savebtn").click(function () {
        //if ($('#createCategory').valid()) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("Create", "Category")',//'/Category/Create',
                data: $("#createCategory").serialize()
            }).done(function (response) {

                $("#tableContiner").html(response);
                $("#createCategory").html("");
                focusAction("tableContiner");

            }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
                swal({
                    title: "Warning",
                    text: "Please enter all required fields",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,

                });
            });
        //}
        //else {
        //    swal({
        //        title: "JS Warning",
        //        text: "Please enter all required fields",
        //        icon: "warning",
        //        buttons: true,
        //        dangerMode: true,

        //    })
        //}
       
    });

 
        //$("#createCategory").validate({
        //    rules: {
        //        "name": {
        //            required: true,
        //            minlength: 5
        //        },
        //        "Description": {
        //            required: true,
           
        //        }
        //    },
        //    messages: {
        //        "name": {
        //            required: "Please, enter a name"
        //        },
        //        "Description": {
        //            required: "Please, enter an Description",
                  
        //        }
        //    }
        
        //});




    $("#cancelbtn").click(function () {
        $("#createCategory").html("");
        focusAction("tableContiner");
    });

    $("#changeimg").change(function () {

        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;

        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }

        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")',//'/Shared/UploadImage',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData:false
        }).done(function (response) {

            console.log(response);

            if (response.Success) {
                $("#ImageURL").val(response.ImageURL);
                $("#imageshow").attr("src",response.ImageURL);
            }

        }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        })
    })
</script>

ClothBazar.Web/Views/Category/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<h4>Are you sure you want to delete this categoty?</h4>
<form method="post">
    <h2>Create Category</h2>

    <label>ID</label>
    <input type="text" name="name" value="@Model.ID" />

    <button type="submit">Yes Delete</button>
</form>

<a href="/Index">Cancel</a>

ClothBazar.Web/Views/Category/Edit.cshtml
@model EditCategoryViewModels
@{
    ViewBag.Title = "Edit";
    var truechecked = Model.isFeatured ? "checked" : string.Empty;
    var falsechecked = !Model.isFeatured ? "checked" : string.Empty;

    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/Images/Default_image.jpg";

}

<h2>Edit</h2>

@*<form method="post">
    <h2>Create Category</h2>

    <label>Name</label>
    <input type="text" name="name" value="@Model.Name"/>

     
    <label>Description</label>
    <input type="text" name="Description" value="@Model.Description" />

    <input name="IsFeatured" type="checkbox" checked="checked" value="True" style="display:inline" />

    <label>Is Featured</label>
    <input name="IsFeatured" type="radio" value="True" checked /> True
    <input name="IsFeatured" type="radio" value="False" /> False <br />
    <br />
    <button type="submit">Save</button>
</form>*@

<form id="editCategory">
    <div class="mb-2 ml-5">
        <input type="hidden" name="ID" value="@Model.ID"/>

        <label>Name</label>
        <input class="form-control form-control-lg" type="text" name="name" value="@Model.Name" />

        <label>Description</label>
        <input class="form-control form-control-lg" type="text" name="Description" value="@Model.Description" />


        <label>Is Featured</label><br />
        <input name="IsFeatured" type="radio" value="True" @truechecked /> True
        <input name="IsFeatured" type="radio" value="False" @falsechecked /> False
        <br />

        <label>Image</label>
        <input class="form-control form-control-lg" type="hidden" id="ImageURL" name="ImageURL" value="@Model.ImageURL" />
        <input class="form-control form-control-lg" id="changeimg" type="file" name="image" accept=".png .jpg" />
        <div class="thumb w-25 h-25 ">
            <img id="imageshow" src="@imageURL" />
        </div>

        <br />
        <button id="editbtn" type="button" class="btn btn-primary form-control form-control-lg">Update</button>
        <button id="cancelbtn" type="button" class="btn btn-primary form-control form-control-lg">Cancel</button>

    </div>
</form>

<script>
    $("#changeimg").change(function () {

        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;

        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }

        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")',//'/Shared/UploadImage',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        }).done(function (response) {

            console.log(response);

            if (response.Success) {
                $("#ImageURL").val(response.ImageURL);
                $("#imageshow").attr("src", response.ImageURL);
            }

        }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        })
    })

    $("#editbtn").click(function () {
        $.ajax({
            type:'POST',
            url:  '@Url.Action("Edit", "Category")',//'/Category/Edit',
            data: $("#editCategory").serialize()
        }).done(function (response) {
            $("#tableContiner").html(response);
            $("#editCategory").html("");
            focusAction("tableContiner");

        }).fail(function (XMLHttpRequest,textStatus,errorThrown) {
            alert("FAIL");
        })
    });

    $("#cancelbtn").click(function () {
        $("#AddProductCon").html("");
        focusAction("tableContiner");
    });

</script>

ClothBazar.Web/Views/Category/Index.cshtml
@{
    ViewBag.Title = "Categories";
}

<h2>Category Home Page</h2>
<section class="flat-row flat-iconbox">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section margin_bottom_17">
                    <h2 class="title">
                        Category
                    </h2>
                </div>
            </div>
        </div>
        @{
            Html.RenderAction("CategoryList");
            //  Html.RenderAction("Create");
        }
    </div>
</section>
   
  

ClothBazar.Web/Views/Category/_CategoryList.cshtml
@model ClothBazar.Web.HomeModelViews.CategorySearchViewModels



<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
<script src="~/Scripts/jquery-1.10.2.js"></script>



<div>
    <div id="tableContiner">
        <div>
            <form class="form-inline" method="post">
                <div class="form-group mb-2 ml-5">
                    <input id="searchtxt" class="form-control" name="Search" value="@Model.SearchTerm" />
                    <button class="btn btn-primary ml-1" type="button" id="search">Search</button>
                    <button class="btn btn-primary ml-1" type="button" id="reset">Reset</button>
                    <button class="btn btn-primary ml-1" type="button" id="NewBtn">New</button>
                </div>
            </form>
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th class="font-weight-bold">Category Name</th>
                    <th class="font-weight-bold">Products</th>
                    <th class="font-weight-bold wrap-td">Actions</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Categories != null && Model.Categories.Count > 0)
            {
                foreach (var category in Model.Categories)
                {
                        <tr>
                            <td>@category.Name</td>
                            <td>@category.Products.Count</td>
                            <td class="wrap-td">
                                <button class="EditBtn" data-id="@category.ID">Edit</button>
                                <button class="DelBtn" data-id="@category.ID">Delete</button>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="3" class="text-danger">Categories found.</td>
                    </tr>
                }
            </tbody>
        </table>
        <div>
            @if (Model.Pager != null && Model.Pager.TotalPages > 1)
            {
                if (Model.Pager.CurrentPage > 1)
                {
                    <button class="pageRecords" data-pageno="1">First</button>
                    <button class="pageRecords" data-pageno="@(Model.Pager.CurrentPage - 1)">Previous</button>
                }
                for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                {
                    string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                    <button class="@activeClass pageRecords" data-pageno="@page">@page</button>
                }
                if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                {
                    <button class="pageRecords" data-pageno="@(Model.Pager.CurrentPage + 1)">Next</button>
                    <button class="pageRecords" data-pageno="@(Model.Pager.EndPage)">Last</button>
                }
            }

        </div>
    </div>
   
</div>

<div id="AddProductCon">

</div>


<script>

    $(".pageRecords").click(function () {
        $.ajax({
            url: '@Url.Action("CategoryList", "Category")',
            data: {
                pageNo: $(this).attr("data-pageNo"),
                search:'@Model.SearchTerm'

            }
        })
        .done(function (response) {
            $("#tableContiner").html(response);
        })

        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        })
    });

    $("#search").click(function () {
        var txtvalue = $("#searchtxt").val();
        $.ajax({
            url: '@Url.Action("CategoryList", "Category")',//'/Category/CategoryList',
            data: {
                search: txtvalue
            }
        }).done(function (data) {

            $("#tableContiner").html(data);
            //alert(data);
        }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });

    });

    $("#NewBtn").click(function () {
        $.ajax({
            url: '@Url.Action("Create", "Category")',//'/Category/Create'
        })
        .done(function (response) {
            $("#AddProductCon").html(response);
            focusAction("AddProductCon");
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert('Fail');
        });
    });

    $("#reset").click(function () {
        var txtvalue = '';
        $.ajax({
            url: '@Url.Action("CategoryList", "Category")',
            data: {
                search: txtvalue
            }
        }).done(function (data) {

            $("#tableContiner").html(data);
        }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        })

    });

    $(".EditBtn").click(function () {
        $.ajax({
            url: '@Url.Action("Edit", "Category")',//'/Category/Edit',
            data: {
                ID: $(this).attr('data-id')
            }
        })
        .done(function (response) {
            $("#AddProductCon").html(response);
            focusAction("AddProductCon");
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        })
    });

    $(".DelBtn").click(function () {

        var confirmsms = confirm("Are you sure you want to delete this category?");

        if (confirmsms) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("Delete", "Category")',//'/Category/Delete',
                data: {
                    ID: $(this).attr('data-id')
                }
            })
            .done(function (response) {
                $("#tableContiner").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("FAIL");
            })
        }

    });
    function focusAction(controlToFocus) {
        $('html , body').animate({
            scrollTop: $("#" + controlToFocus).offset().top - 100
        }, 1000);
    }
</script>